Lapis/Controllers/ApplicationTypeController.cs
using Lapis_Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Lapis_Utility;
using Lapis_DataAcess;
using Lapis_DataAcess.Repository;
using Lapis_DataAcess.Repository.IRepository;
using Microsoft.EntityFrameworkCore;

namespace Lapis.Controllers
{
    [Authorize(Roles =GlobalConst.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository _appTypeRepo;

        public ApplicationTypeController(IApplicationTypeRepository appTypeRepo)
        {
            _appTypeRepo = appTypeRepo;
        }
        public IActionResult Index()
        {
            IEnumerable<ApplicationType> result = _appTypeRepo.GetAll();

            return View(result);
        }
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType applicationType)
        {
            _appTypeRepo.Add(applicationType);
            _appTypeRepo.Save();
            return RedirectToAction("Index");
        }

        // get categories for u then u can Edit one of them 
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var result = _appTypeRepo.Find(id);

            if (result is null)
            {
                return NotFound();
            }

            return View(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType applicationType)
        {
            if (ModelState.IsValid)
            {
                _appTypeRepo.Update(applicationType);
                _appTypeRepo.Save();
                return RedirectToAction("Index");
            }
            else
            {
                return View(applicationType);
            }
        }

        // get category object for u then u can delete  
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var result = _appTypeRepo.Find(id);

            if (result is null)
            {
                return NotFound();
            }

            return View(result);
        }

        public IActionResult DeletePost(int? id)
        {
            var category = _appTypeRepo.Find(id);

            if (category == null)
            { return NotFound(); }

            _appTypeRepo.Remove(category);
            _appTypeRepo.Save();
            return RedirectToAction("Index");
        }
    }
}

Lapis/Views/ApplicationType/Create.cshtml
@model Lapis_Models.ApplicationType

<form method="post" asp-action="Create">
    <div class="border b-3">
        <div class = "form-group row">
            <h2 class="text-info pl-3" > Add Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name" ></label>
                    </div>
                    <div class="col-8">
                        <input asp-for= "Name" class ="form-control" />
                    </div>

                </div>
               
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                             <input type="submit" asp-action="Create" class="btn btn-info w-100" />
                        </div>
                        <div class="col">
                              <a asp-action="Index" class="btn btn-success w-100"> Back </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

Lapis/Views/ApplicationType/Delete.cshtml
@model Lapis_Models.ApplicationType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border b-3">
        <div asp-validation-summary=ModelOnly class ="text-danger"></div>
        <div class = "form-group row">
            <h2 class="text-info pl-3" > Edit ApplicationType </h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name" ></label>
                    </div>
                    <div class="col-8">
                        <input asp-for= "Name" disabled class ="form-control" />
                        
                    </div>

                </div>
                
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                             <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                              <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

<!--client side validation does not hit the server -->
@section Scripts
{
    @{ <partial name ="_ValidationScriptsPartial"/> }
}

Lapis/Views/ApplicationType/Edit.cshtml
@model Lapis_Models.ApplicationType

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div class="border b-3">
        <div asp-validation-summary=ModelOnly class ="text-danger"></div>
        <div class = "form-group row">
            <h2 class="text-info pl-3" > Edit Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name" ></label>
                    </div>
                    <div class="col-8">
                        <input asp-for= "Name" class ="form-control" />
                        <span asp-validation-for="Name" class ="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                             <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                              <a asp-action="Index" class="btn btn-success w-100"> <i class="fas fa-sign-out-alt"></i> Back </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

<!--client side validation does not hit the server -->
@section Scripts
{
    @{ <partial name ="_ValidationScriptsPartial"/> }
}

Lapis/Views/ApplicationType/Index.cshtml
@model IEnumerable<Lapis_Models.ApplicationType>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary">
                 <i class="fas fa-plus"></i> &nbsp; Create New ApplicationType
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                       Name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var obj in Model)
                {
                <tr>
                    <td width="50%">@obj.Name</td>
    
                    <td class="text-center">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                <i class="fas fa-edit"></i>   
                            </a>
                            <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                <i class="far fa-trash-alt"></i>  
                            </a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p> No Application Types exist.</p>
    }

</div>